inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  
AllCops:
  TargetRubyVersion: 2.6.3
  Exclude:
    - vendor/**/*
    - db/schema.rb
    - tmp/**/*
    - db/migrate/*

# 日本語でのコメントを許可
AsciiComments:
  Enabled: false

# 複数行での「lambda」で「->」による省略記法を許可
Lambda:
  Enabled: false

# モジュール名::クラス名の定義を許可
ClassAndModuleChildren:
  Enabled: false


# クラスにコメントを残さない
Documentation:
  Enabled: false
  
# "Missing top-level class documentation comment."を無効
Style/Documentation:
  Enabled: false